version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: app
    env_file:
      - ./app/.env
    environment:
      - CHOKIDAR_USEPOLLING=1
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: worker
    env_file:
      - ./worker/.env
    depends_on:
      - mongo
      - redis
    command: npm run dev:watch
    volumes:
      - ./worker:/usr/src/app
      - worker_node_modules:/usr/src/app/node_modules

  mongo:
    image: mongo:6
    container_name: deflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=deflow

  redis:
    image: redis:7
    container_name: deflow-redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  worker_node_modules:
  app_node_modules:
